controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
	
})
let mySprite: Sprite = null
adventure.setScoreOverride(adventure.Currency.Potions, 100)
adventure.addToTextlog("As you walk next to the near-night sky, the hoods of the trees bend slightly, covering the bright rays of the sun.")
adventure.addToTextlog("Then, all of a sudden, a bush spawns in front of you, dark pixie dust emitting around the green blob.")
adventure.addToTextlog("You hear faint whispers from the bush as you crouch closer to it. ")
adventure.addToTextlog("Before the bush suddenly warps into a green pixie, her green bright wings leaving off a sprinkle of dark dust. ")
adventure.addToTextlog("\"Hello... Mortal.\"")
let green_pixie = sprites.create(img`
    ........................
    ...fffffff..............
    ...f77777ff....fffffff..
    ..ff777777f...ff66666ff.
    ..f7777777fffff7777766f.
    ..f77777ff77666f777766f.
    ..f6677f77777766f77776f.
    ..ff667f77777776f77776f.
    ...ffff7777777766f777ff.
    ......f7777777777fffff..
    ......f7ee777ee7ef......
    ......fbe1feef1eef......
    ......fcd1f44f1dcf......
    .......fb444444bf.......
    ......ffff4444fffffff...
    ....fc111ffffff111c6f...
    ....f1b1bf9979fb1b16f...
    ....fb6b6f9777f6b6b6f...
    ..c.f6666f9979f66666f...
    ....ff666ff999ff6666f.c.
    .....ff6fffffff.ff66f...
    ......f6f....c...ff6f..c
    ...c..fff.......c.f6f.c.
    ........c...c.....fff...
    `, SpriteKind.Player)
green_pixie.setPosition(142, 100)
sprites.destroy(green_pixie)
adventure.addToTextlog("You step back, but as you reach for your sword, you feel nothing.")
adventure.addToTextlog("Your sword is gone. A pixie, ever so small could kill you with a touch. ")
adventure.addToTextlog("What do you do?")
adventure.addToTextlog("The pixie smirks. \"Your sword.. Oops.. Must've destroyed it.\"")
adventure.addToTextlog("You have two choices. A weapon from your pocket, or.. run.")
adventure.addToTextlog("Press A/Space Bar to grab your weapon.")
adventure.addToTextlog("Press B/Enter to run. ")
if (controller.A.isPressed()) {
    adventure.setScoreOverride(adventure.Currency.Potions, 100)
    adventure.addToTextlog("In an instinct you reach in your pocket, finding a handy dagger.")
    mySprite = sprites.create(img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ...........eeee...............
        ........eee2442e.......ee.....
        ......ee24444444e.....eeee....
        ...eee2244444442eeeeeee44ee...
        .ee5555555555555e44e44e44ee...
        ...eee2444444444e44e44eeee....
        ......ee24444442eeeeee.ee.....
        ........eee2442e..............
        ...........eeee...............
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        `, SpriteKind.Player)
    adventure.addToTextlog("The glazed, golden, dagger shone in your hands. ")
    adventure.addToTextlog("This wasn't your average ")
}
